# ----------------------------------------------------------------------------
# Copyright © {% now 'local', '%Y' %}, {{ cookiecutter.full_name }}
#
# Licensed under the terms of the {{ cookiecutter.open_source_license }}
# ----------------------------------------------------------------------------

# See: https://pre-commit.com/
repos:
-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    - id: black
      verbose: true
