name: Linux tests

on:
  push:
    paths:
      - '**'

  pull_request:
    paths:
      - '**'

jobs:
  build:
    name: 'Py${{ matrix.PYTHON_VERSION }}'
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: '${{ matrix.PYTHON_VERSION }}'
    strategy:
      fail-fast: false 
      matrix:
        PYTHON_VERSION: ['3.8']
    steps:
      - name: Checkout Pull Requests
        uses: actions/checkout@v2
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: '${{ matrix.PYTHON_VERSION }}'
      - name: Update pip
        run: pip install -U pip
      - name: Install dependencies
        run: pip install cookiecutter
      - name: Run default cookiecutter
        run: |
          cd ..
          cookiecutter spyder5-plugin-cookiecutter --no-input
          cd spyder-boilerplate
          python setup.py develop
